### ISSUE TITLE
Java issue

### ISSUE THREAD

**Issue by chenxihuang** [compomics/compomics-utilities#31]
Hi:

I have the error with Java, it keeps showing following:

[2018-10-24 11:21:35.894] Loading external PTM file 'novor_mods.txt'.
[2018-10-24 11:21:36.214] Loading built-in novor file 'trypsin-cid-trap'.
[2018-10-24 11:21:36.948] De Novo on 'C:\Users\p276244\Desktop\05-LC_MS_Proteomics\整理Proteolytic System\Peaks\Low mass set\08_3K_2_3.mgf'.
[2018-10-24 11:21:39.237] Elapsed time: 00:02, 735 / 8864 completed (8.3%), speed: 352.4 specs/sec (21143/min)
[2018-10-24 11:21:42.284] Elapsed time: 00:05, 936 / 8864 completed (10.6%), speed: 182.4 specs/sec (10942/min)
[2018-10-24 11:21:46.373] Elapsed time: 00:09, 1568 / 8864 completed (17.7%), speed: 170.0 specs/sec (10202/min)
[2018-10-24 11:21:49.464] Elapsed time: 00:12, 1903 / 8864 completed (21.5%), speed: 154.6 specs/sec (9274/min)
java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.concurrent.FutureTask.report(Unknown Source)
	at java.util.concurrent.FutureTask.get(Unknown Source)
	at N.run(Unknown Source)
Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
	at h.c(Unknown Source)
	at h.a(Unknown Source)
	at R.a(Unknown Source)
	at R.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.concurrent.FutureTask.report(Unknown Source)
	at java.util.concurrent.FutureTask.get(Unknown Source)
	at N.run(Unknown Source)
Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
	at h.c(Unknown Source)
	at h.a(Unknown Source)
	at R.a(Unknown Source)
	at R.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

could you help me out of this?
Thanks for your time :)

Regards
Chenxi

**Comment by hbarsnes** [comment]
Hi Chenxi,

It seems like this issue comes from running Novor via DeNovoGUI right? For future issues with DeNovoGUI it would be much better if you opened an issue directly under the DeNovoGUI issue tracker: https://github.com/compomics/denovogui/issues.

However, as the above error is happening inside Novor I would rather recommend contacting the Novor developers directly (https://www.rapidnovor.com) as there is not much we can do with issues inside Novor.

But as a general tip I would recommend having a closer look at your de novo settings to perhaps try to figure out which paramater may have cause the issue. This will make it easier for the Novor developers to locate the problem on their end.

I will now close this issue, but please don't hesitate to open a new one under the DeNovoGUI issue tracker if you have further questions.

Best regards,
Harald
