### ISSUE TITLE
PeptideMapperCLI NullPointerException

### ISSUE THREAD

**Issue by dm-hansen** [compomics/compomics-utilities#45]
Investigating use of PeptideMapper. The documentation is out of date as of v5.0 (wrong path and name of the executable), but having found the correct path for the PeptideMapper**CLI** class, the "quick-start" example fails:
```
$ java -cp ../utilities-5.0.0.jar com.compomics.cli.peptide_mapper.PeptideMapperCLI -p ./exampleFiles/PeptideMapping/yeast.fasta ./exampleFiles/PeptideMapping/yeast-pep-1k.csv results.csv
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "com.compomics.util.parameters.identification.search.SearchParameters.setModificationParameters(com.compomics.util.parameters.identification.search.ModificationParameters)" because the return value of "com.compomics.util.parameters.identification.IdentificationParameters.getSearchParameters()" is null
     at com.compomics.cli.peptide_mapper.PeptideMapperCLI.handleParameters(PeptideMapperCLI.java:363)
     at com.compomics.cli.peptide_mapper.PeptideMapperCLI.main(PeptideMapperCLI.java:85)
```
 
Is this a bug in all the v5.x releases or has the command-line interface changed such that the documentation is out of date?

**Comment by hbarsnes** [comment]
Thanks for letting us know! It indeed was the case that the PeptideMapper wiki nor the code had been kept up to date after the move to v5.x. I've now updated both the documentation and the code and deployed a new compomics-utilities version (v5.0.32) which should solve the problem. If this is not the case, please let me know and I'll reopen the issue.
