### ISSUE TITLE
IdentificationParametersCLI bug saving .par file in  SearchGUI 2.3.0

### ISSUE THREAD

**Issue by im281** [compomics/compomics-utilities#9]
IdentificationParametersCLI -out gives error below. 

It appears that a input.par file created by the GUI can also not be edited and saved

SearchGUI-2.3.0>java -cp SearchGUI-2.3.0.jar eu.isas.searchgui.cmd.IdentificationParametersCLI -db "C:\folder\myo.fasta" -out "C:/Users//Documents/idparams.par"

java.lang.NullPointerException
at com.compomics.util.preferences.IdentificationParameters.saveIdentificationParameters(IdentificationParameters.java:421)
at com.compomics.util.experiment.identification.parameters_cli.AbstractIdentificationParametersCli.call(AbstractIdentificationParametersCli.java:116)
at com.compomics.util.experiment.identification.parameters_cli.AbstractIdentificationParametersCli.initiate(AbstractIdentificationParametersCli.java:93)
at eu.isas.searchgui.cmd.IdentificationParametersCLI.(IdentificationParametersCLI.java:25)
at eu.isas.searchgui.cmd.IdentificationParametersCLI.main(IdentificationParametersCLI.java:36)

**Comment by hbarsnes** [comment]
This is the same issue as reported in https://github.com/compomics/compomics-utilities/issues/8. I'm therefore closing this issue in order to avoid duplicate answers. Please refer to the above issue for further information on the reported issue.
